name: pre-commit

on:
  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    name: pre-commit (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: typescript-learning
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - uses: bahmutov/npm-install@v1
      - uses: pre-commit/action@v2.0.0
