name: tag

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          root: ".bumpversion.cfg"
          regex_pattern: 'current_version = ([0-9]+\.[0-9]+\.[0-9]+)'
